name: MineDI
main: ru.cwcode.tkach.minedi.extension.paper.Main
libraries:
  - "net.bytebuddy:byte-buddy:${bytebuddy.version}"
version: '${project.version}'
api-version: '1.16'
depend: ["CWCommands", "CWConfig"]
softdepend: ["IPMC", "CWConfigWebEditor", "PlaceholderAPI", "ProtocolLib"]